modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/MorphingEquipment/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="morphingequipment"
version="${version}"
displayName="Morphing Equipment"
updateJSONURL="${update_url}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/morphing-equipment"
logoFile="morphingequipment-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''A tool that can morph into contained equipment'''

[[dependencies.morphingequipment]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.morphingequipment]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
